sudo: false
language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
script:
  - bash ci/pylint/get-badge.sh
  - pytest --cov=ndna/ tests/
after_success:
  - codecov
notifications:
  email: false
